### PR TITLE
Fix: ignore deletion error and log error into stderr

### LINKED ISSUE #759: Network Plugin cni failed to set up pod
Hi, 

I have installed kube-egress-gateway on my cluster, however the installation failed due to lack of permissions on the manage identity. 

After the failed installation I get this error message when I try to create or delete any pod on all namespaces in the cluster

Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "0ee20d39941b0e16feee59003d0cee1251f8eeefa0e5829afad23cf54cc8e5bf": plugin type="kube-egress-cni" failed (add): failed to get pod (iperf3-deployment-6b7f6d68cd-sdnw2/default) annotations: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:50051: connect: connection refused"

When I try to delete the pod, it remains in Terminating state

### PR DESCRIPTION
**Pull request by MartinForReal**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix: ignore deletion error and log error into stderr

#### Which issue(s) this PR fixes:

Fixes #759

### CODE REVIEW

File: cmd/kube-egress-cni/main.go [hunk 1]
```diff
@@ -190,67 +189,74 @@ func cmdAdd(args *skel.CmdArgs) error {
...
+	defer conn.Close()
+	client := v1.NewNicServiceClient(conn)
+	_, err = client.NicDel(context.Background(), &v1.NicDelRequest{
+		PodConfig: &v1.PodInfo{
+			PodName:      string(k8sInfo.K8S_POD_NAME),
+			PodNamespace: string(k8sInfo.K8S_POD_NAMESPACE),
+		},
+	})
+	if err != nil {
+		logger.Error(err, "failed to send nicDel request")
```
Comment (feiskyer) [inline cmd/kube-egress-cni/main.go:256]: how do we cleanup them later since error is ignored?

Comment (MartinForReal) [reply cmd/kube-egress-cni/main.go:256]: it should be done in cni manager

Comment (MartinForReal) [reply cmd/kube-egress-cni/main.go:256]: oh, the daemonset has done the cleanup job.

Comment (feiskyer) [reply cmd/kube-egress-cni/main.go:256]: That's great!

**Review by feiskyer — APPROVED** [review]
