### PR TITLE
handle failed VMSS instance update

### LINKED ISSUE #981: VMSS/VM update operations should be retried on failures
VMSS/VM update operations should be retried on failures, e.g. re-PUT VMSS/VM again on next reconcile.

Here are the sample events that VMSS/VM not retried and hence stuck at `failed to find private IP` error:

```
  Warning  ReconcileGatewayVMConfigurationError  11m                gatewayVMConfiguration-controller      failed to update vmss instance(0): GET  xxx 

  Warning  ReconcileGatewayVMConfigurationError    5m38s (x15 over 11m)  gatewayVMConfiguration-controller      failed to find private IP xxx
```

### PR DESCRIPTION
**Pull request by moreOver0**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Updating vmss instance failure is not retried if it happens. Make sure each reconciliation updates vmss instance if vm's state is not expected, or missing required primary IP and secondary IP.

#### Which issue(s) this PR fixes:

Fixes #981

### CODE REVIEW

File: controllers/manager/gatewayvmconfiguration_controller.go [hunk 1]
```diff
@@ -560,13 +560,62 @@ func (r *GatewayVMConfigurationReconciler) reconcileVMSSVM(
 		return "", fmt.Errorf("vmss vm(%s) has empty os profile", to.Val(vm.InstanceID))
 	}
 
+	forceUpdate := false
+	// check LatestModelApplied
+	if vm.Properties.LatestModelApplied != nil && !to.Val(vm.Properties.LatestModelApplied) {
+		forceUpdate = true
```
Comment (feiskyer) [inline controllers/manager/gatewayvmconfiguration_controller.go:566]: Could we only update when there is a failure? 

The reason here is when a vm is added to LB backend pool, it would always be shown as latest model not applied why the model is actually same as VMSS. So this means more APIs would be invoked whenever you PUT VM NIC

File: controllers/manager/gatewayvmconfiguration_controller.go [hunk 2]
```diff
@@ -560,13 +560,62 @@ func (r *GatewayVMConfigurationReconciler) reconcileVMSSVM(
...
+		log.Info("Force update for unexpected VMSS instance LatestModelApplied:false", "vmssInstance", to.Val(vm.ID))
+	}
+
+	// check ProvisioningState
+	if !forceUpdate && vm.Properties.ProvisioningState != nil && !strings.EqualFold(to.Val(vm.Properties.ProvisioningState), "Succeeded") {
+		log.Info(fmt.Sprintf("VMSS instance ProvisioningState %q", to.Val(vm.Properties.ProvisioningState)))
```
Comment (feiskyer) [inline controllers/manager/gatewayvmconfiguration_controller.go:572]: could you add vm name to the log?

File: controllers/manager/gatewayvmconfiguration_controller.go [hunk 3]
```diff
@@ -560,13 +560,62 @@ func (r *GatewayVMConfigurationReconciler) reconcileVMSSVM(
...
+		if strings.EqualFold(to.Val(vm.Properties.ProvisioningState), "Failed") {
```
Comment (feiskyer) [inline controllers/manager/gatewayvmconfiguration_controller.go:573]: could you add a test for ProvisioningState==Failed scenario?

Comment (moreOver0) [reply controllers/manager/gatewayvmconfiguration_controller.go:567]: added to log by `log := log.FromContext(ctx).WithValues("vmssInstance", to.Val(vm.ID), "wantIPConfig", wantIPConfig, "ipPrefixID", ipPrefixID)`

File: controllers/manager/gatewayvmconfiguration_controller.go (hunk 1 above)
Comment (moreOver0) [reply controllers/manager/gatewayvmconfiguration_controller.go]: OK... I do see one more PUT operation because of this `LatestModelApplied`. But it finally achieved `LatestModelApplied:true` after the additional PUT operation.

Comment (moreOver0) [reply controllers/manager/gatewayvmconfiguration_controller.go]: Removed this if block. And let's watch the e2e/runner failures to see if the other checks are enough.
